// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://rcfbzckaanhypnnlxuvo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJjZmJ6Y2thYW5oeXBubmx4dXZvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjgwNDk3OTAsImV4cCI6MjA4MzYyNTc5MH0.2jBbCB_mIIT03PQOl3zapXo_QmshLyfV1GS0dxaGEfM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);